#!/usr/bin/env ruby
$LOAD_PATH << "./lib" << "../lib"

require "test_15_versus_and"
require "test_16_array_item_removal"
require "test_17_home_on_the_range"
require "test_18_substracting_out_the_sugar"
require "test_19_theres_no_way_this_works_version_2"
require "test_20_or_equal"
require "test_21_brackets_and_searches"
require "test_22_alternate_array_notation"
require "test_23_set_intersection"
require "test_24_getters_and_setters"
require "test_25_queue_continuum"
require "test_26_ternary_operator"
require "test_27_caution_case"
require "test_28_the_limits_of_probability"

VersusAndTest.test_versus_and
HomeOnTheRangeTest.test_home_on_the_range
ArrayItemRemovalTest.test_array_item_removal
SubstractingOutTheSugarTest.test_substracting_out_the_sugar
TheresNoWayThisWorksVersion2Test.test_theres_no_way_this_works_version2
OrEqualTest.test_or_equal
BracketsAndSearchesTest.test_brackets_and_searches
AlternateArrayNotationTest.test_alternate_array_notation
SetIntersectionTest.test_set_intersection
GettersAndSettersTest.test_getters_and_setters
QueueContinuumTest.test_queue_continuum
TernaryOperatorTest.test_ternary_operator
CautionCaseTest.test_caution_case
TheLimitsOfProbabilityTest.test_the_limits_of_probability
